### ISSUE TITLE
currentStyle Sling Binding determination in MockAemSlingBindings is different then the AEM implementation

### ISSUE THREAD

**Issue by rubnig** [wcm-io/io.wcm.testing.aem-mock#10]
The current implementation of `MockAemSlingBindings` is different from the implementation provided by Adobe.
The behaviour difference resides in adding the binding for the `currentStyle`.

The Adobe implementation (`WCMBindingsValuesProvider`) tries to resolve the `currentStyle` by trying to load a `ContentPolicy` with the `ContentPolicyManager` from the requested resource (`request.getResource()`) but the AEM Mocks implementation is not executing this step, see: https://github.com/wcm-io/io.wcm.testing.aem-mock/blob/293e85a0fa02a0d538289f0f6a38643f4d60dcd0/core/src/main/java/io/wcm/testing/mock/aem/MockDesign.java#L65

This results in test failures when making use of `@ChildResourceFromRequest` from ACS Commons, because the `ContentPolicy` is trying to be loaded from the wrong resource (parent resource of the requested child resource) in this case.

**Comment by rubnig** [comment]
I've provided a potential fix for this issue in https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/11, so the AEM Mocks implementation is aligned with the AEM implementation for this case.

**Comment by stefanseifert** [comment]
thanks for the contribution!

i looked a bit deeper what is AEM doing internally at this position and discovered that more was lacking, AEM supported three more sling bindings properties, two of them related to content policies, which AEM mocks did not support yet. the way of resolving currentStyle with content policies in use also changed, but different than your implementation proposal from #11.

i've added a new PR https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/12 that should get AEM mocks in sync with the current AEM implementation, and merged the unit tests from your PR into it - they pass.

please cross-check if PR https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/12 also works for your in your projects.

**Comment by rubnig** [comment]
Good catch @stefanseifert, I've just tested your branch and see that it also resolves our issue!

Think we can merge https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/12 :)
