### ISSUE TITLE
Outline minimum required Java version for AEM Mock versions

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.testing.aem-mock#13]
It was a surprise to me that 5.2 and newer require Java 11 (https://wcm.io/testing/aem-mock/changes-report.html#a5.2.0).
Would be good to add the minimum Java version to the version support matrix in https://wcm.io/testing/aem-mock/

**Comment by stefanseifert** [comment]
it's listed in the changelog, and globally here: https://wcm.io/platforms.html
but it's fine to include it in the support matrix table as well
