### ISSUE TITLE
Add support for Experience Fragments

### ISSUE THREAD

**Issue by royteeuwen** [wcm-io/io.wcm.testing.aem-mock#22]

**Comment by royteeuwen** [comment]
@stefanseifert  any chance you could have a look at this :) ?

**Comment by stefanseifert** [comment]
sure! (but probably after adaptTo() ...)

**Comment by prestoncrawford** [comment]
Out of curiosity, what's the "adaptTo()" functionality being worked on? I'm part of a team that's currently trying to write mocks against Experience Fragments and we're having some issues with a custom injector.

**Comment by stefanseifert** [comment]
@prestoncrawford  the PR from #23 comes with an adapter factory implementation, so it's possible to adapt AEM page objects to `ExperienceFragment` or `ExperienceFragmentVariation` interfaces
