### ISSUE TITLE
Creating a Nested CaConfig with MockContextAwareConfig.writeConfiguration together with the PagePersistenceStrategy needs additional information (jcr:content/) in the sub configuration name 

### ISSUE THREAD

**Issue by rubnig** [wcm-io/io.wcm.testing.aem-mock#25]
In https://issues.apache.org/jira/browse/SLING-11839 creating Nested CaConfigs via `MockContextAwareConfig.writeConfiguration` was added to https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin.

This works fine, but there is an issue with storing the configurations via `io.wcm.caconfig.extensions.persistence.impl.PagePersistenceStrategy` (from https://wcm.io/caconfig/extensions/).

I've added an example in https://github.com/wcm-io/io.wcm.samples/commit/49d2f8420c11e02660ca599f9789f39f191c7ca4, with a broken test.
By default the nested configuration gets stored in the wrong place:

at `/conf/wcm-io-samples/en/sling:configs/io.wcm.samples.core.example.NestedConfig/sub`
instead of `/conf/wcm-io-samples/en/sling:configs/io.wcm.samples.core.example.NestedConfig/jcr:content/sub`.

There is a workaround currently possible by prefixing the nested configuration name with `jcr:content/`, see the following example:

```java
MockContextAwareConfig.writeConfiguration(context, context.currentPage().getPath(), NestedConfig.class,
        "stringParam", "value1",
        "jcr:content/sub", ImmutableList.of(
                ImmutableValueMap.of("subStringParam", "v1", "intParam", 5,
                        "stringArrayParam", new String[] {"v1a","v1b"}),
                ImmutableValueMap.of("subStringParam", "v2")
        )
);
```

I am not 100% sure if this is intended behavior or a bug in the combination of AEM Mocks / CaConfig Extensions / Sling Testing CaConfig Mock Plugin. 

At least it is caused by the concatenation within https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin/blob/master/src/main/java/org/apache/sling/testing/mock/caconfig/ConfigurationPersistHelper.java#L111.

What do you think @stefanseifert, do we need to update the documentation for this specific case or does this need to be fixed?

**Comment by stefanseifert** [comment]
i personally never bother about actually activating the PagePersistenceStrategy also in the unit tests, as it does not make any difference for the tests if they interact only with the caconfig APIs. but you are right, it seems to clash here.

the workaround is ugly and should not be required. i have to think about a solution to support both ways with and without such a custom strategy.

**Comment by rubnig** [comment]
Maybe it is an idea to move the logic for determining a nested config / nested config collection name to `org.apache.sling.caconfig.spi.ConfigurationPersistenceStrategy2` so it always needs to be implemented and handled by the PersistenceStrategy implementations. 

So these methods https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin/blob/master/src/main/java/org/apache/sling/testing/mock/caconfig/ConfigurationPersistHelper.java#L110C3-L126C6 will be replaced by retrieving the nested configuration name from the persistence strategy itself?

**Comment by stefanseifert** [comment]
i've fixes the root cause in https://issues.apache.org/jira/browse/SLING-12192, and added a test case with the page persistence strategy in https://github.com/wcm-io/io.wcm.testing.wcm-io-mock.caconfig/pull/2

please cross-check with Context-Aware Configuration Mock Plugin 1.5.3-SNAPSHOT

**Comment by rubnig** [comment]
Thanks @stefanseifert, 

I just double checked it with the sample test from the issue description and it succeeds.

```sh
[INFO] Running io.wcm.samples.core.example.NestedConfigModelTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 s -- in io.wcm.samples.core.example.NestedConfigModelTest
```

I've closed the ticket as it is resolved :)
