### ISSUE TITLE
Testing Resource Resolver Login Failures

### ISSUE THREAD

**Issue by schaefa** [wcm-io/io.wcm.testing.aem-mock#28]
I want to test my code when the obtaining of the Service Resource Resolver fails but I cannot access or reset the Resource Resolver Factory with my own.

**Comment by stefanseifert** [comment]
that's not really an issue of aem-mock, but rather of sling-mock.

did you try to register your own (mock of) ResourceResolverFactory service implementation with a higher ranking?
