### ISSUE TITLE
Clarify context instantiation with AemContextExtension

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.testing.aem-mock#37]
According to https://wcm.io/testing/aem-mock/usage.html#JUnit_5_AEM_Context_JUnit_Extension

> It is recommended to define the AemContext field as non-static field and use `@BeforeEach` and `@AfterEach` methods if you want to execute setup or tear down code for each test run. Since version 3.0.0 AEM Mocks also supports static AemContext fields and `@BeforeAll` and `@AfterAll` methods...

However if one instantiates the context variable only in the `@BeforeEach` or the `@BeforeAll` you have now two different contexts which may lead to subtle issues (i.e. only one seeing certain resources).

For example with this code:

```
@ExtendWith({AemContextExtension.class})
class MyTest {

    private AemContext context;

    @BeforeEach
    void before() {
        context = new AemContext();
        context.load().json(myTestContent.json, "/content/test");
        context.addModelsForClasses(MyModel.class);
    }

    @Test
    void givenPage_whenLoaded_thenInitializeAllData() {
        //  Model is now based on two different contexts!
        context.request().adaptTo(MyModel.class)
   }
}
```

And the model looks like this
```
@Model(adaptables = SlingHttpServletRequest.class)
public class MyModel {
   @OSGiService
   private ResourceResolverFactory resourceResolverFactory;

   @Self
    private SlingHttpServletRequest request;

    @PostConstruct
    void init() {
        request.getResourceResolver().getResource("/content/test") // return populated resource
        resourceResolverFactory.getResourceResolver(null).getResource("/content/test") // returns null 
    }
```

As soon as one moves the instantiation of `context` to the declaration it works as expected.
That usage scenaria should somehow be caught and lead to a more verbose exception.

At least the documentation should be extended that creating the context in helper methods is not working as expected!

**Comment by kwin** [comment]
See also the related https://issues.apache.org/jira/browse/SLING-12278.

**Comment by stefanseifert** [comment]
as commented in https://issues.apache.org/jira/browse/SLING-12278 for now i will only update the documentation, PR for aem-mock: https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/39
