### ISSUE TITLE
JUnit 5 vs Junit 4: extra depenency and setup needed to make test work

### ISSUE THREAD

**Issue by senn** [wcm-io/io.wcm.testing.aem-mock#42]
We had an existing test that adapts a Resource (MockResource) to a Sling Model.  This model has a list of another Sling model injected by `@ChildResource`.  This inner model some fields injected with different annotations, one of them being `@AemObject private TagManager tagManager`.

In JUnit 4 with this io.wcm dependency, this worked and the model was fully initialized:
```
<dependency>
    <groupId>io.wcm</groupId>
    <artifactId>io.wcm.testing.aem-mock</artifactId>
    <version>2.6.0</version>
    <scope>test</scope>
</dependency>
```

However in JUnit 5, the list of inner models remained `null` and it took me a deepdive into `ModelAdapterFactory`, etc... to discover the inner problem was that no injector was found for `wcm-io-aem-object`. 

I checked in some io.wcm github repo's to see how you guys test models annotated with that value and I got it working by having to add an extra dependency (commons) + registering some extra services in my `AemContext`:
```
<dependency>
    <groupId>io.wcm</groupId>
    <artifactId>io.wcm.sling.commons</artifactId>
    <version>1.6.4</version>
    <scope>test</scope>
</dependency>



//needed to resolve wcm-io injectors
context.registerService(RequestContext.class, requestContext);
context.registerInjectActivateService(new ModelsImplConfiguration(), "requestThreadLocal", true);
context.registerInjectActivateService(new AemObjectInjector());
```

What is the reason for this?  Is there a better way to do this?

**Comment by stefanseifert** [comment]
is it correct you are using aem mocks 2.6.0, a version that is 5 years old? i would recommend to update your dependencies.

regarding the actual problem: if you use other wcm.io modules in you unit test, make sure to register the related AEM mocks plugin which automatically registers the related services like AemObjectInjector in the test context.

in this case you need the mock helper pugin for sling extensions https://wcm.io/testing/wcm-io-mock/sling/ - here is a list of all plugins https://wcm.io/testing/ - and here an example how to register the plugins centrally to your project:
https://github.com/wcm-io/io.wcm.samples/blob/develop/bundles/core/src/test/java/io/wcm/samples/core/testcontext/AppAemContext.java

**Comment by senn** [comment]
Thank you, that was indeed what I was looking for.  Curious how I missed that documentation 🤔.  And yes, those old dependencies have been updated during the junit5 upgrade.
