### ISSUE TITLE
Externalizer does not map paths according to resolver mappings

### ISSUE THREAD

**Issue by HitmanInWis** [wcm-io/io.wcm.testing.aem-mock#44]
The Externalizer in AEM Mock does not honor resource resolver mappings, whereas it does on a running AEM server.

As an example if I have a resource resolver mapping of `/content/mysite/abc:/custompath`

- Calling `resourceResolver.map("/content/mysite/abc/page")` returns `/custompath/page` as expected
- Calling `externalizer.publishLink(resourceResolver, "/content/mysite/abc/page")` should return `<domain>/custompath/page` but instead it returns `<domain>/content/mysite/abc/page`

This creates a situation where tests have to check for an externalized URL string that is not actually what we expect on the running server.

**Comment by stefanseifert** [comment]
implemented with #45

**Comment by HitmanInWis** [comment]
Amazing response time :D   Thanks!
